# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CashbackObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'amount': 'AllOfCashbackObjectAmount'
    }

    attribute_map = {
        'description': 'description',
        'amount': 'amount'
    }

    def __init__(self, description=None, amount=None):  # noqa: E501
        """CashbackObject - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._amount = None
        self.discriminator = None
        self.description = description
        self.amount = amount

    @property
    def description(self):
        """Gets the description of this CashbackObject.  # noqa: E501

        A brief description of why this cashback was paid.   # noqa: E501

        :return: The description of this CashbackObject.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CashbackObject.

        A brief description of why this cashback was paid.   # noqa: E501

        :param description: The description of this CashbackObject.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def amount(self):
        """Gets the amount of this CashbackObject.  # noqa: E501

        The total amount of cashback paid, represented as a positive value.   # noqa: E501

        :return: The amount of this CashbackObject.  # noqa: E501
        :rtype: AllOfCashbackObjectAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this CashbackObject.

        The total amount of cashback paid, represented as a positive value.   # noqa: E501

        :param amount: The amount of this CashbackObject.  # noqa: E501
        :type: AllOfCashbackObjectAmount
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CashbackObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CashbackObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
