# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HoldInfoObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'AllOfHoldInfoObjectAmount',
        'foreign_amount': 'AllOfHoldInfoObjectForeignAmount'
    }

    attribute_map = {
        'amount': 'amount',
        'foreign_amount': 'foreignAmount'
    }

    def __init__(self, amount=None, foreign_amount=None):  # noqa: E501
        """HoldInfoObject - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._foreign_amount = None
        self.discriminator = None
        self.amount = amount
        self.foreign_amount = foreign_amount

    @property
    def amount(self):
        """Gets the amount of this HoldInfoObject.  # noqa: E501

        The amount of this transaction while in the `HELD` status, in Australian dollars.   # noqa: E501

        :return: The amount of this HoldInfoObject.  # noqa: E501
        :rtype: AllOfHoldInfoObjectAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this HoldInfoObject.

        The amount of this transaction while in the `HELD` status, in Australian dollars.   # noqa: E501

        :param amount: The amount of this HoldInfoObject.  # noqa: E501
        :type: AllOfHoldInfoObjectAmount
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def foreign_amount(self):
        """Gets the foreign_amount of this HoldInfoObject.  # noqa: E501

        The foreign currency amount of this transaction while in the `HELD` status. This field will be `null` for domestic transactions. The amount was converted to the AUD amount reflected in the `amount` field.   # noqa: E501

        :return: The foreign_amount of this HoldInfoObject.  # noqa: E501
        :rtype: AllOfHoldInfoObjectForeignAmount
        """
        return self._foreign_amount

    @foreign_amount.setter
    def foreign_amount(self, foreign_amount):
        """Sets the foreign_amount of this HoldInfoObject.

        The foreign currency amount of this transaction while in the `HELD` status. This field will be `null` for domestic transactions. The amount was converted to the AUD amount reflected in the `amount` field.   # noqa: E501

        :param foreign_amount: The foreign_amount of this HoldInfoObject.  # noqa: E501
        :type: AllOfHoldInfoObjectForeignAmount
        """
        if foreign_amount is None:
            raise ValueError("Invalid value for `foreign_amount`, must not be `None`")  # noqa: E501

        self._foreign_amount = foreign_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HoldInfoObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HoldInfoObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
