# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListAccountsResponseLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'prev': 'str',
        'next': 'str'
    }

    attribute_map = {
        'prev': 'prev',
        'next': 'next'
    }

    def __init__(self, prev=None, next=None):  # noqa: E501
        """ListAccountsResponseLinks - a model defined in Swagger"""  # noqa: E501
        self._prev = None
        self._next = None
        self.discriminator = None
        self.prev = prev
        self.next = next

    @property
    def prev(self):
        """Gets the prev of this ListAccountsResponseLinks.  # noqa: E501

        The link to the previous page in the results. If this value is `null` there is no previous page.   # noqa: E501

        :return: The prev of this ListAccountsResponseLinks.  # noqa: E501
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this ListAccountsResponseLinks.

        The link to the previous page in the results. If this value is `null` there is no previous page.   # noqa: E501

        :param prev: The prev of this ListAccountsResponseLinks.  # noqa: E501
        :type: str
        """
        if prev is None:
            raise ValueError("Invalid value for `prev`, must not be `None`")  # noqa: E501

        self._prev = prev

    @property
    def next(self):
        """Gets the next of this ListAccountsResponseLinks.  # noqa: E501

        The link to the next page in the results. If this value is `null` there is no next page.   # noqa: E501

        :return: The next of this ListAccountsResponseLinks.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this ListAccountsResponseLinks.

        The link to the next page in the results. If this value is `null` there is no next page.   # noqa: E501

        :param next: The next of this ListAccountsResponseLinks.  # noqa: E501
        :type: str
        """
        if next is None:
            raise ValueError("Invalid value for `next`, must not be `None`")  # noqa: E501

        self._next = next

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListAccountsResponseLinks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListAccountsResponseLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
