# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RoundUpObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'AllOfRoundUpObjectAmount',
        'boost_portion': 'AllOfRoundUpObjectBoostPortion'
    }

    attribute_map = {
        'amount': 'amount',
        'boost_portion': 'boostPortion'
    }

    def __init__(self, amount=None, boost_portion=None):  # noqa: E501
        """RoundUpObject - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._boost_portion = None
        self.discriminator = None
        self.amount = amount
        self.boost_portion = boost_portion

    @property
    def amount(self):
        """Gets the amount of this RoundUpObject.  # noqa: E501

        The total amount of this Round Up, including any boosts, represented as a negative value.   # noqa: E501

        :return: The amount of this RoundUpObject.  # noqa: E501
        :rtype: AllOfRoundUpObjectAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this RoundUpObject.

        The total amount of this Round Up, including any boosts, represented as a negative value.   # noqa: E501

        :param amount: The amount of this RoundUpObject.  # noqa: E501
        :type: AllOfRoundUpObjectAmount
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def boost_portion(self):
        """Gets the boost_portion of this RoundUpObject.  # noqa: E501

        The portion of the Round Up `amount` owing to boosted Round Ups, represented as a negative value. If no boost was added to the Round Up this field will be `null`.   # noqa: E501

        :return: The boost_portion of this RoundUpObject.  # noqa: E501
        :rtype: AllOfRoundUpObjectBoostPortion
        """
        return self._boost_portion

    @boost_portion.setter
    def boost_portion(self, boost_portion):
        """Sets the boost_portion of this RoundUpObject.

        The portion of the Round Up `amount` owing to boosted Round Ups, represented as a negative value. If no boost was added to the Round Up this field will be `null`.   # noqa: E501

        :param boost_portion: The boost_portion of this RoundUpObject.  # noqa: E501
        :type: AllOfRoundUpObjectBoostPortion
        """
        if boost_portion is None:
            raise ValueError("Invalid value for `boost_portion`, must not be `None`")  # noqa: E501

        self._boost_portion = boost_portion

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoundUpObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoundUpObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
