# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebhookDeliveryLogResourceRelationships(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'webhook_event': 'WebhookDeliveryLogResourceRelationshipsWebhookEvent'
    }

    attribute_map = {
        'webhook_event': 'webhookEvent'
    }

    def __init__(self, webhook_event=None):  # noqa: E501
        """WebhookDeliveryLogResourceRelationships - a model defined in Swagger"""  # noqa: E501
        self._webhook_event = None
        self.discriminator = None
        self.webhook_event = webhook_event

    @property
    def webhook_event(self):
        """Gets the webhook_event of this WebhookDeliveryLogResourceRelationships.  # noqa: E501


        :return: The webhook_event of this WebhookDeliveryLogResourceRelationships.  # noqa: E501
        :rtype: WebhookDeliveryLogResourceRelationshipsWebhookEvent
        """
        return self._webhook_event

    @webhook_event.setter
    def webhook_event(self, webhook_event):
        """Sets the webhook_event of this WebhookDeliveryLogResourceRelationships.


        :param webhook_event: The webhook_event of this WebhookDeliveryLogResourceRelationships.  # noqa: E501
        :type: WebhookDeliveryLogResourceRelationshipsWebhookEvent
        """
        if webhook_event is None:
            raise ValueError("Invalid value for `webhook_event`, must not be `None`")  # noqa: E501

        self._webhook_event = webhook_event

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebhookDeliveryLogResourceRelationships, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebhookDeliveryLogResourceRelationships):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
