# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebhookDeliveryLogResourceAttributesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status_code': 'int',
        'body': 'str'
    }

    attribute_map = {
        'status_code': 'statusCode',
        'body': 'body'
    }

    def __init__(self, status_code=None, body=None):  # noqa: E501
        """WebhookDeliveryLogResourceAttributesResponse - a model defined in Swagger"""  # noqa: E501
        self._status_code = None
        self._body = None
        self.discriminator = None
        self.status_code = status_code
        self.body = body

    @property
    def status_code(self):
        """Gets the status_code of this WebhookDeliveryLogResourceAttributesResponse.  # noqa: E501

        The HTTP status code received in the response.   # noqa: E501

        :return: The status_code of this WebhookDeliveryLogResourceAttributesResponse.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this WebhookDeliveryLogResourceAttributesResponse.

        The HTTP status code received in the response.   # noqa: E501

        :param status_code: The status_code of this WebhookDeliveryLogResourceAttributesResponse.  # noqa: E501
        :type: int
        """
        if status_code is None:
            raise ValueError("Invalid value for `status_code`, must not be `None`")  # noqa: E501

        self._status_code = status_code

    @property
    def body(self):
        """Gets the body of this WebhookDeliveryLogResourceAttributesResponse.  # noqa: E501

        The payload that was received in the response body.   # noqa: E501

        :return: The body of this WebhookDeliveryLogResourceAttributesResponse.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this WebhookDeliveryLogResourceAttributesResponse.

        The payload that was received in the response body.   # noqa: E501

        :param body: The body of this WebhookDeliveryLogResourceAttributesResponse.  # noqa: E501
        :type: str
        """
        if body is None:
            raise ValueError("Invalid value for `body`, must not be `None`")  # noqa: E501

        self._body = body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebhookDeliveryLogResourceAttributesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebhookDeliveryLogResourceAttributesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
