# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebhookEventResourceRelationships(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'webhook': 'WebhookEventResourceRelationshipsWebhook',
        'transaction': 'WebhookEventResourceRelationshipsTransaction'
    }

    attribute_map = {
        'webhook': 'webhook',
        'transaction': 'transaction'
    }

    def __init__(self, webhook=None, transaction=None):  # noqa: E501
        """WebhookEventResourceRelationships - a model defined in Swagger"""  # noqa: E501
        self._webhook = None
        self._transaction = None
        self.discriminator = None
        self.webhook = webhook
        if transaction is not None:
            self.transaction = transaction

    @property
    def webhook(self):
        """Gets the webhook of this WebhookEventResourceRelationships.  # noqa: E501


        :return: The webhook of this WebhookEventResourceRelationships.  # noqa: E501
        :rtype: WebhookEventResourceRelationshipsWebhook
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook):
        """Sets the webhook of this WebhookEventResourceRelationships.


        :param webhook: The webhook of this WebhookEventResourceRelationships.  # noqa: E501
        :type: WebhookEventResourceRelationshipsWebhook
        """
        if webhook is None:
            raise ValueError("Invalid value for `webhook`, must not be `None`")  # noqa: E501

        self._webhook = webhook

    @property
    def transaction(self):
        """Gets the transaction of this WebhookEventResourceRelationships.  # noqa: E501


        :return: The transaction of this WebhookEventResourceRelationships.  # noqa: E501
        :rtype: WebhookEventResourceRelationshipsTransaction
        """
        return self._transaction

    @transaction.setter
    def transaction(self, transaction):
        """Sets the transaction of this WebhookEventResourceRelationships.


        :param transaction: The transaction of this WebhookEventResourceRelationships.  # noqa: E501
        :type: WebhookEventResourceRelationshipsTransaction
        """

        self._transaction = transaction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebhookEventResourceRelationships, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebhookEventResourceRelationships):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
