# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tags_api import TagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tags_get(self):
        """Test case for tags_get

        List tags  # noqa: E501
        """
        pass

    def test_transactions_transaction_id_relationships_tags_delete(self):
        """Test case for transactions_transaction_id_relationships_tags_delete

        Remove tags from transaction  # noqa: E501
        """
        pass

    def test_transactions_transaction_id_relationships_tags_post(self):
        """Test case for transactions_transaction_id_relationships_tags_post

        Add tags to transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
