# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_accounts_response import ListAccountsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListAccountsResponse(unittest.TestCase):
    """ListAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAccountsResponse(self):
        """Test ListAccountsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_accounts_response.ListAccountsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
