# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.categories_api import CategoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_categories_get(self):
        """Test case for categories_get

        List categories  # noqa: E501
        """
        pass

    def test_categories_id_get(self):
        """Test case for categories_id_get

        Retrieve category  # noqa: E501
        """
        pass

    def test_transactions_transaction_id_relationships_category_patch(self):
        """Test case for transactions_transaction_id_relationships_category_patch

        Categorize transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
