# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.webhooks_api import WebhooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhooks_get(self):
        """Test case for webhooks_get

        List webhooks  # noqa: E501
        """
        pass

    def test_webhooks_id_delete(self):
        """Test case for webhooks_id_delete

        Delete webhook  # noqa: E501
        """
        pass

    def test_webhooks_id_get(self):
        """Test case for webhooks_id_get

        Retrieve webhook  # noqa: E501
        """
        pass

    def test_webhooks_post(self):
        """Test case for webhooks_post

        Create webhook  # noqa: E501
        """
        pass

    def test_webhooks_webhook_id_logs_get(self):
        """Test case for webhooks_webhook_id_logs_get

        List webhook logs  # noqa: E501
        """
        pass

    def test_webhooks_webhook_id_ping_post(self):
        """Test case for webhooks_webhook_id_ping_post

        Ping webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
